### ISSUE TITLE
Target

### ISSUE THREAD

**Issue by sanchezquibus** [MaxCam/viz-atlas-latencymon#1]
Hi
I'm new using GIt-hub. I'm looking at the code and I'm trying to find where I can change the local host and the target to get the Latency between them.
Thanks

**Comment by massimocandela** [comment]
Hi,
This is a tool for visualising RIPE Atlas measurements. See https://atlas.ripe.net for more information.

**Comment by sanchezquibus** [comment]
Hi Massimo,
I know the goal of this tool. I wanted to know how use it between two AS
from RIPE.

2016-04-06 15:05 GMT+02:00 Massimo Candela notifications@github.com:

> Hi,
> This is a tool for visualising RIPE Atlas measurements. See
> https://atlas.ripe.net for more information.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/MaxCam/viz-atlas-latencymon/issues/1#issuecomment-206360733

## 

_Marc Sànchez Quibus_

**Comment by massimocandela** [comment]
Hi,
You should create a RIPE Atlas measurement involving a probe and a host in
the two ASes and after load the measurement ID in the LatencyMON widget.

Ciao,
Massimo

2016-04-06 16:41 GMT+02:00 sanchezquibus notifications@github.com:

**Comment by sanchezquibus** [comment]
Hi Massimo,
Sorry for being late in answer and really thanks for your help, it was
really useful.
Thankfully,
Marc

2016-04-08 11:02 GMT+02:00 Massimo Candela notifications@github.com:

> Hi,
> You should create a RIPE Atlas measurement involving a probe and a host in
> the two ASes and after load the measurement ID in the LatencyMON widget.
> 
> Ciao,
> Massimo
> 
> 2016-04-06 16:41 GMT+02:00 sanchezquibus notifications@github.com:
> 
> > Hi Massimo,
> > I know the goal of this tool. I wanted to know how use it between two AS
> > from RIPE.
> > 
> > 2016-04-06 15:05 GMT+02:00 Massimo Candela notifications@github.com:
> > 
> > > Hi,
> > > This is a tool for visualising RIPE Atlas measurements. See
> > > https://atlas.ripe.net for more information.
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/MaxCam/viz-atlas-latencymon/issues/1#issuecomment-206360733
> > 
> > 
> > ## 
> > 
> > _Marc Sànchez Quibus_
> > 
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/MaxCam/viz-atlas-latencymon/issues/1#issuecomment-206408272
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/MaxCam/viz-atlas-latencymon/issues/1#issuecomment-207336149

## 

_Marc Sànchez Quibus_
